package com.olivetticlub.cashregisterapp.coupons

import kotlin.random.Random

class InMemoryCoupons {

    fun retrieve(): Coupon {
        return Coupon(randomMerchant(), randomDescription(), randomAddress())
    }
}

fun randomMerchant(): String {
    return listOf(
        "Calzolaio Bertucci",
        "La Rinascente",
        "I Due Leoni",
        "Don Jhon",
        "Sorelle Ramonda",
        "Incontro"
    ).random()
}

fun randomDescription(): String {
    return """${listOf(5, 10, 15, 20).random()}% di sconto su un prodotto a tua scelta"""
}

fun randomAddress(): String {
    return listOf(
        "Via ADALBERTO CATENA",
        "Viale ADAMO MICKIEWICZ",
        "Via AGNELLO",
        "Via ALESSANDRO MANZONI",
        "Viale ALESSANDRO PETOFI",
        "Viale ALESSANDRO PUSKIN",
        "Via ALESSANDRO VOLTA",
        "Via ANCONA",
        "Via ANDEGARI",
        "Via ANDREA APPIANI",
        "Via ANFITEATRO",
        "Via Degli ANGIOLI",
        "Via Dell' ANNUNCIATA",
        "Via ANTONIO BERETTA",
        "Largo ANTONIO GREPPI",
        "Via ARCO",
        "Via ARRIGO BOITO",
        "Via BAGUTTA",
        "Via BAGUTTINO",
        "Piazza BELGIOIOSO",
        "Via BIGLI",
        "Via BORGONUOVO",
        "Via BORGOSPESSO",
        "Largo BORTOLO BELOTTI",
        "Via BOSCHETTI",
        "Via Dei BOSSI",
        "Piazzetta Di BRERA",
        "Via BRERA",
        "Via BROLETTO",
        "Foro BUONAPARTE",
        "Via CARLO CATTANEO",
        "Piazza CARLO MIRABELLO",
        "Via CARLO PORTA",
        "Piazza Del CARMINE",
        "Via Del CARMINE",
        "Via CASE ROTTE",
        "Via CASTELFIDARDO",
        "Piazza CASTELLO",
        "Piazza CAVOUR",
        "Via CERNAIA",
        "Via CESARE MANGILI",
        "Via Dei CHIOSTRI",
        "Via CIOVASSINO",
        "Via CIOVASSO",
        "Vicolo CIOVASSO",
        "Galleria CIRO FONTANA",
        "Largo CLAUDIO TREVES",
        "Via CLERICI",
        "Via CROCE ROSSA",
        "Via CUSANI",
        "Via DANIELE MANIN",
        "Via DELIO TESSA",
        "Largo DE SABATA VICTOR",
        "Viale EMILIO ALEMAGNA",
        "Viale EMILIO ZOLA",
        "Viale ENRICO CONNEAU",
        "Piazzetta ENRICO CUCCIA",
        "Viale ENRICO IBSEN",
        "Via Delle ERBE",
        "Via EUGENIO BALZAN",
        "Viale EUGENIO BEAUHARNAIS",
        "Via FARINE",
        "Via FATEBENEFRATELLI",
        "Via FATEBENESORELLE",
        "Viale FEDERICO SCHILLER",
        "Piazza FILIPPO MEDA",
        "Via FILIPPO TURATI",
        "Via FILODRAMMATICI",
        "Via FIORI CHIARI",
        "Via FIORI OSCURI",
        "Vicolo FIORI",
        "Viale FRANCESCO CRISPI",
        "Via FRATELLI GABBA",
        "Via Del GALLO",
        "Via GASTONE PISONI",
        "Viale GEROLAMO GADIO",
        "Via GEROLAMO MORONE",
        "Via GESU'",
        "Corso GIACOMO MATTEOTTI",
        "Via GIACOMO PUCCINI",
        "Via GIAN DOMENICO ROMAGNOSI",
        "Via Dei GIARDINI",
        "Vicolo GIARDINO",
        "Via GIOVANNI BERCHET",
        "Via GIOVANNI LANZA",
        "Passaggio GIOVANNI MALAGODI",
        "Viale GIOVANNI MILTON",
        "Via GIULIANOVA",
        "Via GIUSEPPE BRENTANO",
        "Corso GIUSEPPE GARIBALDI",
        "Via GIUSEPPE MARCORA",
        "Via GIUSEPPE MENGONI",
        "Via GIUSEPPE PARINI",
        "Via GIUSEPPE POZZONE",
        "Via GIUSEPPE SACCHI",
        "Via GIUSEPPE VERDI",
        "Via GOITO",
        "Largo GUIDO DONEGANI",
        "Via IGINIO UGO TARCHETTI",
        "Largo LA FOPPA",
        "Via LANDOLFO",
        "Via Del LAURO",
        "Viale LEGIONE LOMBARDA",
        "Via LEGNANO",
        "Piazza Del LIBERTY",
        "Largo LINO MONTAGNA",
        "Via LOVANIO",
        "Via LUCA BELTRAMI",
        "Via LUCHINO VISCONTI",
        "Via LUIGI ALBERTINI",
        "Viale LUIGI CAMOENS",
        "Via LUIGI ILLICA",
        "Via LUIGI ROSSARI",
        "Via MADONNINA",
        "Viale MALTA",
        "Via MARCO DE MARCHI",
        "Via MARCO FORMENTINI",
        "Via MARCO MINGHETTI",
        "Piazzale MARENGO",
        "Largo MARIA CALLAS",
        "Via MARINA",
        "Via MARINO TOMMASO",
        "Via MARSALA",
        "Piazzetta MAURILIO BOSSI",
        "Via MELONE",
        "Via MERCATO",
        "Viale MICHELE CERVANTES",
        "Via MILAZZO",
        "Viale MOLIERE",
        "Via MONTEBELLO",
        "Via MONTE DI PIETA'",
        "Via MONTENAPOLEONE",
        "Via Della MOSCOVA",
        "Via OMENONI",
        "Via Dell' ORSO",
        "Via PALERMO",
        "Via PALESTRO",
        "Piazza PAOLO FERRARI",
        "Largo PAOLO GRASSI",
        "Piazza PAOLO VI",
        "Via PIERRE E MARIE CURIE",
        "Via PIETRO VERRI",
        "Via PONTACCIO",
        "Via PONTE VETERO",
        "Via PONTIDA",
        "Via PORRONE BASSANO",
        "Bastioni Di PORTA NUOVA",
        "Corso Di PORTA NUOVA",
        "Via Di PORTA TENAGLIA",
        "Bastioni Di PORTA VOLTA",
        "Via PRINCIPE AMEDEO",
        "Via QUINTINO SELLA",
        "Largo RAFFAELE MATTIOLI",
        "Via RAGAZZI DEL '99",
        "Via RENZO BERTONI",
        "Via RIVOLI",
        "Piazzale RODOLFO MORANDI",
        "Via ROVELLO",
        "Via SAN CARPOFORO",
        "Via SAN DALMAZIO",
        "Via SANDRO SANDRI",
        "Piazza SAN FEDELE",
        "Via SAN FERMO",
        "Piazza SAN MARCO",
        "Via SAN MARCO",
        "Via SAN PAOLO",
        "Via SAN PIETRO ALL'ORTO",
        "Via SAN PRIMO",
        "Via SAN PROSPERO",
        "Via SAN PROTASO",
        "Via SAN RAFFAELE",
        "Piazza SAN SIMPLICIANO",
        "Via SAN SIMPLICIANO",
        "Via SANTA MARGHERITA",
        "Via SANT'ANDREA",
        "Piazza SANT'ANGELO",
        "Via SANTA RADEGONDA",
        "Piazza SANT'ERASMO",
        "Via SAN TOMASO",
        "Via SANTO SPIRITO",
        "Piazza Della SCALA",
        "Via SENATO",
        "Via SILVIO PELLICO",
        "Via SOLFERINO",
        "Via Della SPIGA",
        "Via STATUTO",
        "Via STEFANO JACINI",
        "Via TIVOLI",
        "Via TOMMASO DA CAZZANIGA",
        "Via TOMMASO GROSSI",
        "Via UGO FOSCOLO",
        "Via ULRICO HOEPLI",
        "Via VARESE",
        "Via VASTO",
        "Via Del VECCHIO POLITECNICO",
        "Bastioni Di Porta VENEZIA",
        "Corso VENEZIA",
        "Piazza VENTICINQUE APRILE",
        "Piazza VENTICINQUE APRILE",
        "Galleria VITTORIO EMANUELE II",
        "Viale WOLFANGO GOETHE"
    ).random() + """, ${Random.nextInt(0, 100)}, Milano"""
}
